### ISSUE TITLE
ACCELERATOR - Issues

### ISSUE THREAD

**Issue by Patricia-Torres** [pedrojovelli/AgoraPartnerships#106]
- Change you want or you get icon (currently the same)
- Mentors button linking to Network rather than mentors

![20](https://user-images.githubusercontent.com/43677737/46230735-dd6c0500-c33f-11e8-83ef-1320dbd17dbe.jpg)

![21](https://user-images.githubusercontent.com/43677737/46230855-3f2c6f00-c340-11e8-8b0b-55f5d3566676.jpg)

**Comment by robanquieri** [comment]
@pedrojovelli need to provide the new icon.
