### ISSUE TITLE
Add Google Code (Tag Manager)

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#107]
Eu não conheço isso aqui. Sabe o que é ?

É igual Google Analytics?

Se puder, add, please.

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5F6M7DR');</script>

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5F6M7DR"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by pedrojovelli** [comment]
Mike.

Disseram que o Código do Google não está rolando ...

Enviaram isso novamente:


Copy and paste this code as the first item into the <HEAD> of every webpage you want to track. If you already have a Global Site Tag on your page, simply add the config line from the snippet below to your existing Global Site Tag.


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-126851659-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-126851659-1');
</script>

**Comment by robanquieri** [comment]
Feito
