### ISSUE TITLE
COMMUNITY (Spanish) - Photos are not showing up

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#108]
Lots of missing photos on Spanish version

![screen shot 2018-10-15 at 10 30 44 am](https://user-images.githubusercontent.com/15367213/46953911-87000580-d065-11e8-9084-8bf9683928ee.png)

**Comment by robanquieri** [comment]
The name of the images is wrong on spreadsheet. For example "DiegoA.png" is the wrong name of the image, the correct it is DiegoAlvarez-Agora-115.png.

https://docs.google.com/spreadsheets/d/1z9DyCfnEAjO12yDfK-In_eiTRMSkloYWcvKXJ5Y1lQQ
