### ISSUE TITLE
Menu Estranho na versão Espanhol

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#123]
Mike.

Pode colocar para entrar na versão do HAMBURGER MENU antes de ter esse tipo de quebra no menu?

![screen shot 2018-10-18 at 2 13 49 pm](https://user-images.githubusercontent.com/15367213/47172030-b4a4b300-d2e0-11e8-971c-3dc7b324bdc9.png)

**Comment by robanquieri** [comment]
Diminuir o nome no WP, direto no menu ESP.
