### ISSUE TITLE
Agora Growth Consulting - FAQ link

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#125]
http://agora2030.org/entrepreneurs/agora-growth-consulting/

Link FAQ. Pode linkar par ao FAQ desta página?

Você possui este link?

**Comment by robanquieri** [comment]
Não possuo.

**Comment by pedrojovelli** [comment]
aqui !

http://agora2030.org/growth-consulting-faq/
