### ISSUE TITLE
Link opens in english instead of spanish

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#138]
**Pitch bootcamp** button goes to detailed bootcamp page in English instead of Spanish

PAGE:
http://agora2030.org/esp/emprendedores/crecimiento-agora-bootcamps/

**Comment by pedrojovelli** [comment]
![screen shot 2018-11-06 at 23 23 26](https://user-images.githubusercontent.com/15367213/48104507-fdce8f80-e21a-11e8-923f-4e20963b08fb.png)

**Comment by robanquieri** [comment]
Done
