### ISSUE TITLE
JOB BOARD

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#139]
Mike.

Para Job board.

Eles queriam só mudar o título para espanhol quando clicasse ...
e no caso chamar as ofertas de trabalho em inglês ou em espanhol ... misturado (caso tenha nas 2 linguas ...)

é um comportamento diferente para esta página.

**Comment by robanquieri** [comment]
Não é possível.

**Comment by pedrojovelli** [comment]
Ok. Obrigado. Já notificamos o time da AGORA. Aguardamos retorno.
