### ISSUE TITLE
JOB BOARD - Ajuste para a descrição dos trabalhos

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#150]
Mike.

Eles gostariam de saber se é possível colocar um texto menor para cada preview do JOB BOARD.

O que acontece agora é que a página JOB BOARD está chamando todo o texto. 

Se você puder preparar um esquema para eles cadastrarem tipo umas 3 linhas de descrição do trabalho antes do usuário clicar e ver todo o post.

![screen shot 2018-11-08 at 12 15 39](https://user-images.githubusercontent.com/15367213/48204046-142a3780-e350-11e8-8e33-cfb59a1a8e8e.png)

**Comment by robanquieri** [comment]
Pode-se limitar a quantidade de palavras.

**Comment by pedrojovelli** [comment]
Pode fazer o seguinte ?

Limitar em 35 palavras e eu irei orientá-los a digitarem essa prévia do post no início.

Uma pergunta. Seria possível que essa prévia não aparecesse no post? ...só aparecesse no JOB BOARD?

**Comment by robanquieri** [comment]
Limitei para 35, me avisa se quiser esconder o texto.

**Comment by pedrojovelli** [comment]
Blz.
