### ISSUE TITLE
Pergunta sobre traduções

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#159]
Mike.

O esquema de tradução está um pouco diferente do que você e a Elysa haviam me mostrado.

Sabe se rolou algum update?

Eu preciso traduzir para espanhol aquelas frases que você mudou donate pra support.

![screen shot 2018-11-19 at 13 43 33](https://user-images.githubusercontent.com/15367213/48717734-271af280-ec01-11e8-9744-c1516e0a1d88.png)

**Comment by robanquieri** [comment]
Não tem nada de diferente ai, você precisa clicar em no primeiro "Agora2018" pra acessar as traduções. Você quem não anotou isso.

**Comment by pedrojovelli** [comment]
thx
