### ISSUE TITLE
Add image to Mobile Parallax - ACCELERATOR

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#17]
- DESKTOP PARALLAX 1 and 2
 - MOBILE PARALLAX 1 and 2

**PHOTOS HERE:**
https://drive.google.com/drive/folders/1u11MhGGy95PBLLfKg6qrc3W8wV33XIRu?usp=sharing

**Comment by robanquieri** [comment]
Só tinha as imagens mobile na pasta.

**Comment by pedrojovelli** [comment]
tudo bem. As do desktop já estão ok.

**Comment by robanquieri** [comment]
done
