### ISSUE TITLE
Change 3 menu links on Mobile

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#19]
Could you do only on mobile the following:

FOR ENTREPRENEURS

FOR INVESTORS

FOR PARTNERS

![screenshot_20180904-162011_chrome 1](https://user-images.githubusercontent.com/15367213/45054498-943bd480-b063-11e8-9698-c08af7a605c4.jpg)

**Text from Elysa:**

_

> Does this Nav bar make sense to you?  Should it say “For Entrepreneurs” “For Investors” etc or is it intuitive? Should the order of this change at all?

_

**Comment by robanquieri** [comment]
O menu é alterado diretamente pelo WordPress, porem não é possível alterar somente para o mobile.

**Comment by pedrojovelli** [comment]
Ok.

Por favor, se puder alterar para:

- FOR ENTREPRENEURS

- FOR INVESTORS

- FOR PARTNERS

**Comment by robanquieri** [comment]
done
