### ISSUE TITLE
Reduce font-size on subheadings

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#20]
Please, reduce font-size on subheadings from 26px to 23px.

**Some subheading examples:** (title texts in blue)

![screen shot 2018-09-04 at 7 13 15 pm](https://user-images.githubusercontent.com/15367213/45060745-b93a4280-b077-11e8-99a9-4046bff3c99a.png)

![screen shot 2018-09-04 at 7 20 19 pm](https://user-images.githubusercontent.com/15367213/45060741-b2abcb00-b077-11e8-8984-17a69cf1fffc.png)

**Comment by robanquieri** [comment]
done
