### ISSUE TITLE
Change Parallax image in PRIORITY INVESTOR NETWORK

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#22]
Page:
http://banquieri.com/investors/priority-investor-network/

Second parallax of the page:
![br_priority-investor-network-1_desktop](https://user-images.githubusercontent.com/15367213/45456556-a6e88600-b6c1-11e8-9a8d-6ddc7af34b1e.jpg)

**Comment by robanquieri** [comment]
Faltou a desktop

**Comment by pedrojovelli** [comment]
ignora essa issue
