### ISSUE TITLE
HOME PAGE - Change Text

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#23]
Old text:
See the impact of the Agora community across industries, regions, and SDGs.

to

New text:
The Agora community's impact across industries, regions, and SDGs.

Reference:
![square](https://user-images.githubusercontent.com/15367213/45456925-085d2480-b6c3-11e8-81c0-c68e6984e94d.jpg)

**Comment by robanquieri** [comment]
done
