### ISSUE TITLE
HOME PAGE - Change image

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#24]
Please, replace that Zuckerberg photo with this one:

![bl_home_desktop](https://user-images.githubusercontent.com/15367213/45457163-1d868300-b6c4-11e8-8ea9-bf2cdd238578.jpg)

**Comment by robanquieri** [comment]
Faltou a mobile

**Comment by robanquieri** [comment]
Duplicate issue.
