### ISSUE TITLE
AGORA COMMUNITY - Add image parallax

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#25]
Please, add this image:
![agoracommunity_header_img](https://user-images.githubusercontent.com/15367213/45457441-4c512900-b6c5-11e8-9549-397ad9a4f790.jpg)

**Comment by robanquieri** [comment]
Faltou a mobile

**Comment by pedrojovelli** [comment]
![agora_banner_mob](https://user-images.githubusercontent.com/15367213/45911243-114aa600-bde7-11e8-9e1d-a0b9783445b3.jpg)
