### ISSUE TITLE
AGORA COMMUNITY Page - Read More button

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#26]
The 'read more' button's function was to hide parte of the texts from the Agora Community members.

It's currently just taking you to the current agorapartnerships.org website.

![screen shot 2018-09-12 at 10 49 47 pm](https://user-images.githubusercontent.com/15367213/45462502-6e0ada00-b6de-11e8-833d-f500082d0dbb.png)

Please, adjust it to show about 5 lines of the profile and not show the button.
if it does have more than some certain number of characters, then the 'read more' button shows up.

If you have any better suggestion for the application of the button in order to have a balance between the profile texts, please, feel free to suggest / apply.

**Comment by robanquieri** [comment]
done
