### ISSUE TITLE
Agora Nicaragua Parallax

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#30]
Mike.

Please, can you replace the current header banner on NICARAGUA's page for this one:

![Uploading nicaragua_parallax.jpg…]()

**Comment by robanquieri** [comment]
O link está errado...

**Comment by pedrojovelli** [comment]
![nicaragua_parallax](https://user-images.githubusercontent.com/15367213/45911299-c2514080-bde7-11e8-828b-3bee05f155ff.jpg)
