### ISSUE TITLE
AGORA GROWTH CONSULTING - Add more serious images

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#40]

**Comment by pedrojovelli** [comment]
Mike.
On this page:
http://banquieri.com/entrepreneurs/agora-growth-consulting/

Please, add this image at the top:

![growth_consulting_desktop](https://user-images.githubusercontent.com/15367213/45845435-7923c280-bcfb-11e8-92ea-e06370e782ef.jpg)


![growth_consulting_mobile](https://user-images.githubusercontent.com/15367213/45845546-d3bd1e80-bcfb-11e8-8462-82aed11d1670.jpg)

**Comment by robanquieri** [comment]
@pedrojovelli you reopened this issue, but don't put any information.

**Comment by pedrojovelli** [comment]
Yes.

Please, put the image above onto the first banner of this page:

![screen shot 2018-09-26 at 8 52 05 am](https://user-images.githubusercontent.com/15367213/46078104-988e7580-c169-11e8-9429-13f88e9fc6b6.png)
