### ISSUE TITLE
Carrossel - Agora Growth Bootcamp

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#42]
Carrossel.

Arrow buttons are not working.

The drag works normally, but the arrows don't.

Please, can you pull the arrows out ot of the squares and make them clickable?

![screen shot 2018-09-19 at 5 28 05 pm](https://user-images.githubusercontent.com/15367213/45779501-912f0f80-bc31-11e8-8036-96b80b374381.png)

**Comment by robanquieri** [comment]
Don't work because the category "Upcoming Bootcamps" have only one post, the drag should not work, but works, it's fixes when have more 4 or more posts . Pull arrows out of square reflect at others carousels on website. My suggestion it's hide the carousel until have 4 or more posts.

**Comment by pedrojovelli** [comment]
Please, hide the arrows by now. So they can pull it back later when it has more content.
