### ISSUE TITLE
FAQ link on footers

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#49]
Page: http://banquieri.com/entrepreneurs/vpo/

**Most of the FAQ links on footers are showing extra margins.**

Please, if you can check that on other pages either.

![margem_margem](https://user-images.githubusercontent.com/15367213/45780912-10721280-bc35-11e8-8ff7-7139ce913107.jpg)

**Comment by robanquieri** [comment]
done
