### ISSUE TITLE
Inside Pages Columns Bullets

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#5]
Hi Rogerio.

I'd like to ask you to squeeze a little bit the space for the content.

Here's a reference pointing specifically the spacing taking as a reference the PSD mockup:

![examples](https://user-images.githubusercontent.com/15367213/44876572-dcc84c00-ac77-11e8-8dbc-73fb05b65146.jpg)

Here're the pages that have 2 cards/columns:

- Partners
- Get-Involved
- Our Work
- Agora Chile

**Comment by robanquieri** [comment]
done
