### ISSUE TITLE
Investors Page - Reducing margin

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#50]
Please, leave just about 45px margin

![imageimage](https://user-images.githubusercontent.com/15367213/45781197-b7ef4500-bc35-11e8-8ee7-14f410689501.jpg)

**Comment by robanquieri** [comment]
Sorry, reduce margin where? I believe this image is wrong right?

**Comment by pedrojovelli** [comment]
foi mal.

Puxei a imagem errada pra adicionar.
