### ISSUE TITLE
Question About AGORA COMMUNITY

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#56]
These must be filled up into the WORDPRESS Admin ?
![screen shot 2018-09-19 at 6 19 27 pm](https://user-images.githubusercontent.com/15367213/45782223-9e9bc800-bc38-11e8-83b7-5f23986f2af1.png)

**Comment by robanquieri** [comment]
Need to fill the field "role" on this spreadsheet https://docs.google.com/spreadsheets/d/1z9DyCfnEAjO12yDfK-In_eiTRMSkloYWcvKXJ5Y1lQQ

I put a fallback, if don't have this field filled don't show nothing.
