### ISSUE TITLE
AGORA CHILE - News Carrossel Photos

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#59]
Is it possible to set a height standard for not have these vertical photos breaking the carrossel grid ?

![screen shot 2018-09-19 at 6 32 56 pm](https://user-images.githubusercontent.com/15367213/45782860-8331bc80-bc3a-11e8-84bd-832d74d48dcc.png)

**Comment by robanquieri** [comment]
done
