### ISSUE TITLE
Three Columns margins

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#6]
Please, check the margins between columns and a few of the titles.
Reduce text sizes as well as described on the image below:

![three_column](https://user-images.githubusercontent.com/15367213/44877574-c7085600-ac7a-11e8-8652-0596ada6182a.jpg)

- Agora Growth
- Agora Growth Consulting
- Partners ( icons are two separated from the titles on a few columns)
- Consulting-program (icons are two separated from the titles on a few columns)

**Comment by robanquieri** [comment]
done
