### ISSUE TITLE
Agora Chile - Carrossel

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#63]
We'd like to know if the second Carrossel (News from Chile) can't go fro side to side as the carrossel above (Companies)

The same for Agora Nicaragua page.

![screen shot 2018-09-19 at 6 50 01 pm](https://user-images.githubusercontent.com/15367213/45783721-fb00e680-bc3c-11e8-8b9f-45ae66730dfb.png)

![screen shot 2018-09-19 at 6 50 06 pm](https://user-images.githubusercontent.com/15367213/45783725-fd634080-bc3c-11e8-807d-201781aebe5c.png)

**Comment by robanquieri** [comment]
done
