### ISSUE TITLE
Agora Nicaragua/Chile Carrossel

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#65]
is it possible to perhaps reduce the icons in order to show 4 on one line, even if it has a bit of empty space in case of it has less than four ?

This could be a way to keep one standard.

![screen shot 2018-09-19 at 6 56 12 pm](https://user-images.githubusercontent.com/15367213/45784005-ca6d7c80-bc3d-11e8-87b4-e53086ecfb50.png)

**Comment by robanquieri** [comment]
done
