### ISSUE TITLE
Add img on parallax banner

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#68]
Page:
http://banquieri.com/investors/priority-investor-network/

Please, can you add that on the top?
![priority_investor](https://user-images.githubusercontent.com/15367213/45842931-812c3400-bcf4-11e8-9b41-0f6a2e0491e9.jpg)

**Comment by robanquieri** [comment]
Não deveria ter uma versão mobile?
