### ISSUE TITLE
Agora Main Menu Spacing

### ISSUE THREAD

**Issue by jggraing** [pedrojovelli/AgoraPartnerships#69]
Increase the spacing between the menu navigation items on Agora's main menu.

**Comment by pedrojovelli** [comment]
What Jesse says is to make it hits side by side of the top area (logo to the very left and menu to the very right)

**Comment by robanquieri** [comment]
Sorry, I don't understand this issue.

**Comment by pedrojovelli** [comment]
![menu2](https://user-images.githubusercontent.com/15367213/46118037-f6a77100-c1da-11e8-837d-e612836d59b9.jpg)

**Comment by robanquieri** [comment]
done
