### ISSUE TITLE
Replace AGORA logo on Parallax

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#7]
Please, replace the AGORA logo on the homepage. On this parallax:

![screen shot 2018-08-30 at 5 56 54 pm](https://user-images.githubusercontent.com/15367213/44878762-20be4f80-ac7e-11e8-92cd-4f01abe931f0.png)

Here's the SVG logo in WHITE:
https://drive.google.com/file/d/1uFNj3vrmU_09lnNNzd77aWOSdVZJh75_/view?usp=sharing

**Comment by robanquieri** [comment]
done
