### ISSUE TITLE
Adding Space on Partners Page

### ISSUE THREAD

**Issue by jggraing** [pedrojovelli/AgoraPartnerships#71]
On the Partners page, move the line to be centered between the button for "Contact Us to Begin Your Impact Project" and "Stay Current."

**Comment by pedrojovelli** [comment]
![screen shot 2018-09-25 at 4 56 38 pm](https://user-images.githubusercontent.com/15367213/46039401-ff694b80-c0e3-11e8-818f-3c8077320849.png)
