### ISSUE TITLE
Add all Photos for the "Our Community" Page

### ISSUE THREAD

**Issue by jggraing** [pedrojovelli/AgoraPartnerships#72]

**Comment by pedrojovelli** [comment]
Hi Rogerio.

Please, let me know if you need any more info for the photos.

**STAFF**
https://drive.google.com/drive/folders/1qiVYlQLJ6zG66OCTaOAB3MYT-ssR9BUg?usp=sharing

**GLOBAL BOARD**
https://drive.google.com/drive/folders/1wV2vkvaPdRRZ9O9jxrMJHE-WQ-JaYrmI?usp=sharing

**Nicaragua Board Profiles**
https://drive.google.com/drive/folders/1naU_rBi8CvSf-qs0yoSGOejYEu57ykWG?usp=sharing

**Chile Board**
https://drive.google.com/drive/folders/15nAal82oBfaH92fwQxn2F-tZAqgn2uz5?usp=sharing

**Mexico Board**
https://drive.google.com/drive/folders/1lN8UL6zs5XE920_ZahRCluXLDYH_S1bo?usp=sharing


**PRIORITY INVESTOR NETWORK**
https://drive.google.com/drive/folders/1296Yi3pvDcqGV04a_WPJRfN_h6T_tapP?usp=sharing

**MENTORS**
https://drive.google.com/drive/folders/1SjkgPzfQwCva4e8brtK92Unpttw5r2HM?usp=sharing

**Comment by robanquieri** [comment]
I'll upload the images, but you or someone else needs to add the right names of the images on this spreadsheet https://docs.google.com/spreadsheets/d/1z9DyCfnEAjO12yDfK-In_eiTRMSkloYWcvKXJ5Y1lQQ

**Comment by robanquieri** [comment]
All images uploaded.
