### ISSUE TITLE
Add a period at the end of this sentence at the top of "Agora Community." 

### ISSUE THREAD

**Issue by jggraing** [pedrojovelli/AgoraPartnerships#73]
The foundation of Agora Partnerships and the impact we create is a dedicated community of Staff, Consultants, Investors, and Mentors.

**Comment by pedrojovelli** [comment]
![balh](https://user-images.githubusercontent.com/15367213/45984443-83192e80-c037-11e8-91ae-aaf556a860d6.jpg)
