### ISSUE TITLE
Photo Stretching 

### ISSUE THREAD

**Issue by jggraing** [pedrojovelli/AgoraPartnerships#74]
Under the "Agora Chile" page where it says, "News from Chile," we have a few changes needed: 

- We need a standard created with this information so that they are all the same. 

- All of the photos are very stretched. Can that be fixed?

**Comment by pedrojovelli** [comment]
Rogerio, in case there's a specific size of image to be applied. Please, let us know and we'll be happy to help the AGORA stuff to adjust.

![screen shot 2018-09-24 at 4 37 19 pm](https://user-images.githubusercontent.com/15367213/45974648-573a8080-c018-11e8-8b80-f922507717a8.png)

**Comment by pedrojovelli** [comment]
What will be the best sizing for placing these photos?

**Comment by robanquieri** [comment]
390 x 180 px

**Comment by pedrojovelli** [comment]
390 x 230 px 

this size fits perfectly with the other images they've updated !

=)
