### ISSUE TITLE
Spreadsheets that feed information into the website (spreadsheets in a folder)

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#78]
Elysa said that there are spreadsheets that feed information into the website. She would like to have all of those spreadsheets in one folder.

**Comment by robanquieri** [comment]
I put all spreadsheets on this folder https://drive.google.com/drive/folders/1DpjUW97s0wFXbiI0mlwyfAtFILDys2qc
