### ISSUE TITLE
Google Analytics tag

### ISSUE THREAD

**Issue by robanquieri** [pedrojovelli/AgoraPartnerships#81]
Please, provide a tag for Google Analytics.

**Comment by pedrojovelli** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-126470733-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-126470733-1');
</script>

**Comment by robanquieri** [comment]
This tag is for domain agora2030.org?
