### ISSUE TITLE
BUG on Portfolio

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/AgoraPartnerships#82]
![whatsapp image 2018-09-26 at 14 03 56](https://user-images.githubusercontent.com/15367213/46102892-cee9e600-c1a5-11e8-8a10-4984cb3f2982.jpeg)

**Comment by pedrojovelli** [comment]
Here's a video example:

https://drive.google.com/file/d/1qYGfe-kUu5bdH3udF3rL90t_FdaT_xDJ/view?usp=sharing

**Comment by robanquieri** [comment]
done
