### ISSUE TITLE
ENTREPRENEURS - Change one photo

### ISSUE THREAD

**Issue by Patricia-Torres** [pedrojovelli/AgoraPartnerships#91]
Switch the photo of Agora Growth Consulting to something more professional

![6](https://user-images.githubusercontent.com/43677737/46223956-4301c680-c32b-11e8-91fb-89903b67476d.jpg)

**Comment by pedrojovelli** [comment]
![nova_img](https://user-images.githubusercontent.com/15367213/47124638-5e3e6280-d255-11e8-8e31-35db5c1588b8.jpg)
