### ISSUE TITLE
Learning Opportunities

### ISSUE THREAD

**Issue by Patricia-Torres** [pedrojovelli/AgoraPartnerships#99]
Learning opportunities should **not repeat** (should only be those tagged, even if it is just one event)

![13](https://user-images.githubusercontent.com/43677737/46229085-bb23b880-c33a-11e8-9137-3dfb72936ea5.jpg)

**Comment by robanquieri** [comment]
This section show all posts tagged as "Events". I don't have control if are the same event,  the solution it is don't create a new post for the same event.

**Comment by pedrojovelli** [comment]
got it
